### ISSUE TITLE
Banner Images should adhere to both IP Address and Port

### ISSUE THREAD

**Issue by AlienXAXS** [TotemArts/Rx_Launcher#10]
Currently it seems that when a Banner Image is added to the Launcher, any server that the IP Address is hosting gets that banner.

Example:
Click on the AGN Server, see the banner
Click on the CT UK Test Server, see that the banner is the same but should not be.

**Comment by AlienXAXS** [comment]
#14 Pull Request Submitted

**Comment by JAJames** [comment]
Issue resolved by #14
