### ISSUE TITLE
Concurrent Downloads

### ISSUE THREAD

**Issue by JAJames** [TotemArts/Rx_Launcher#12]
As a user, I want to be able to download Renegade X patch data from multiple sources/mirrors concurrently, so that I can download from multiple sources simultaneously and not be restricted to the bandwidth available by a single mirror.

Acceptance Criteria:
- [ ] As mirrors are added to the mirror queue, pop off mirrors into threads until the desired number of mirrors have been reached
- [x] Current server selection algorithm should remain otherwise untouched
- [x] Users should be downloading from up to 4 sources simultaneously

**Comment by JAJames** [comment]
My thoughts on this one is that we queue up all of the files into a queue and have 4 worker threads downloading files. Each worker thread has a mirror assigned. For each worker thread, it downloads 1 file at a time and upon completion pops off another file from the queue and begins downloading.

Roughly:
```csharp
void worker_thread() {
    // Pop mirror off of mirror list

    // While there are files to download
    while (!files.empty()) {
        // Pop file off of list
        // Download file
        // Notify success
    }

    // All files have been downloaded; we're done here
}
```

Most of this refactor will probably be around `WebPatchSource.LoadNew`, `RxPatcher.ApplyPatchFromWeb`, and `UpdateServerSelector.SelectHosts`

**Comment by AlienXAXS** [comment]
#22

**Comment by JAJames** [comment]
Closing this issue since the PR was merged
