### ISSUE TITLE
Kill background/ghost processes before patching

### ISSUE THREAD

**Issue by JAJames** [TotemArts/Rx_Launcher#13]
Occasionally, a user may have multiple instances of the launcher open or have ghost processes in the background while trying to patch. This causes errors because some files (such as launcher videos) are in use and therefore unable to patch.

We should kill all duplicate processes in the same directory before proceeding to patch Renegade X. Launchers in other directories as part of other Renegade X installations should remain unaffected.

**Comment by AlienXAXS** [comment]
Would it not simply be easier to not allow multiple instances of the same application to be loaded during application startup, if they are from the same Assembly Path?

**Comment by JAJames** [comment]
My concern there is that if there's a ghost process in the background, the launcher wouldn't launch? Instead you'd probably have to kill duplicate processes at launch time.

**Comment by AlienXAXS** [comment]
We could do both I suppose.

**Comment by AlienXAXS** [comment]
#15 pushed.

**Comment by JAJames** [comment]
I went and tried testing these changes with a fresh install. After the UE3Redist is finished and the launcher goes to restart, the following error appears:
http://sharex.jessicajames.me/2018-01-09_00-01-47.png

I have not yet testing the self-patcher against this, but that also needs to be tested.

**Comment by AlienXAXS** [comment]
Ah okay, this could easily be fixed the same way other restarts of the launcher are sorted by sending a custom cmdline to it, I'll take a look.

**Comment by AlienXAXS** [comment]
Ah okay, this could easily be fixed the same way other restarts of the launcher are sorted by sending a custom cmdline to it, I'll take a look.

**Comment by AlienXAXS** [comment]
Closing this, I feel it's done.
Feel free to re-open with an explanation if not.
